services:
  app:
    image: egs-backend
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    # environment:
    #   - DEBUG=${DEBUG:-false}
    #   - PORT=${PORT}
    #   - DATABASE_URL=${DATABASE_URL}
    env_file:
      - .env

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5433:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
