services:
  app:
    image: egs-backend
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5430:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
